spring:
  datasource:
    url: jdbc:h2:file:~/tacodb
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
    h2:
      console:
        enabled:  true
        path: /h2-console


org:
  hibernate:
    SQL: debug